from tkinter import *
import random
##### ##### ##### ##### #####
root = Tk()
root.title("TEST")
root.minsize(width=600, height=600)
root.maxsize(width=600, height=600)
##### ##### ##### ##### #####
a1=Label(root,text="name")
a2=Label(root,text="class/champ")
a3=Label(root,text="level")
a4=Label(root,text="creep score")
a5=Label(root,text="kills")
a6=Label(root,text="deaths")
a7=Label(root,text="assists")
a8=Label(root,text="item 1")
a9=Label(root,text="item 2")
a10=Label(root,text="item 3")
a11=Label(root,text="item 4")
a12=Label(root,text="item 5")
a13=Label(root,text="item 6")
##### ##### ##### ##### #####
player_name=StringVar()
player_class=StringVar()
player_level=StringVar()
player_cs=StringVar()
player_kills=StringVar()
player_deaths=StringVar()
player_assists=StringVar()
player_item1=StringVar()
player_item2=StringVar()
player_item3=StringVar()
player_item4=StringVar()
player_item5=StringVar()
player_item6=StringVar()
b1=Entry(root,textvariable=player_name)
b2=Entry(root,textvariable=player_class)
b3=Entry(root,textvariable=player_level)
b4=Entry(root,textvariable=player_cs)
b5=Entry(root,textvariable=player_kills)
b6=Entry(root,textvariable=player_deaths)
b7=Entry(root,textvariable=player_assists)
b8=Entry(root,textvariable=player_item1)
b9=Entry(root,textvariable=player_item2)
b10=Entry(root,textvariable=player_item3)
b11=Entry(root,textvariable=player_item4)
b12=Entry(root,textvariable=player_item5)
b13=Entry(root,textvariable=player_item6)
##### ##### ##### ##### #####
c1=Button(root,text="apply")
c2=Button(root,text="apply")
c3=Button(root,text="apply")
c4=Button(root,text="apply")
c5=Button(root,text="apply")
c6=Button(root,text="apply")
c7=Button(root,text="apply")
c8=Button(root,text="apply")
c9=Button(root,text="apply")
c10=Button(root,text="apply")
c11=Button(root,text="apply")
c12=Button(root,text="apply")
c13=Button(root,text="apply")
##### ##### ##### ##### #####
a1.grid(row=1, column=1)
a2.grid(row=2, column=1)
a3.grid(row=3, column=1)
a4.grid(row=4, column=1)
a5.grid(row=5, column=1)
a6.grid(row=6, column=1)
a7.grid(row=7, column=1)
a8.grid(row=8, column=1)
a9.grid(row=9, column=1)
a10.grid(row=10, column=1)
a11.grid(row=11, column=1)
a12.grid(row=12, column=1)
a13.grid(row=13, column=1)

b1.grid(row=1, column=2)
b2.grid(row=2, column=2)
b3.grid(row=3, column=2)
b4.grid(row=4, column=2)
b5.grid(row=5, column=2)
b6.grid(row=6, column=2)
b7.grid(row=7, column=2)
b8.grid(row=8, column=2)
b9.grid(row=9, column=2)
b10.grid(row=10, column=2)
b11.grid(row=11, column=2)
b12.grid(row=12, column=2)
b13.grid(row=13, column=2)

c1.grid(row=1, column=3)
c2.grid(row=2, column=3)
c3.grid(row=3, column=3)
c4.grid(row=4, column=3)
c5.grid(row=5, column=3)
c6.grid(row=6, column=3)
c7.grid(row=7, column=3)
c8.grid(row=8, column=3)
c9.grid(row=9, column=3)
c10.grid(row=10, column=3)
c11.grid(row=11, column=3)
c12.grid(row=12, column=3)
c13.grid(row=13, column=3)
###############################
